apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - front_deployment.yml
  - front_service.yml
  - back_deployment.yml
  - back_service.yml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  - ingress.yml
  - https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
  - dashboard_user.yml
